### ISSUE TITLE
Differences between this an bugfest's controller?

### ISSUE THREAD

**Issue by samip5** [agabani/tor-operator#157]
I came across this operator first time today when looking for bugfest's one, but what are the differences between them except that this one is coded in Rust?

https://github.com/bugfest/tor-controller

**Comment by agabani** [comment]
agabani/tor-operator is in 0.0.x. Things are generally expected to work but any existing asset can break with any upgrade. I wouldn't advocate for anyone to use it in a production setting if they are expecting a stable contract.

Comparing the docs, bugfest/tor-controller has additional features:
- allows users to modify torrc config
- has authorized client support
- doesn't run tor as root

**Comment by samip5** [comment]
Did not notice that yours was running tor as root..
