### ISSUE TITLE
access to control port of an OnionService / exposing of port inside cluster as service

### ISSUE THREAD

**Issue by some0ne2** [agabani/tor-operator#208]
I already found the comparison sheet of this repo "against" bugfests repo.

I would like to use the control port on an OnionService to be able to kill specific onion curcuits to prevent flooding attacks.
Is it possible to expose this port using this repo / any hints on how to do this?
Using bugfests library it's not possible at the moment.
Seems like this is a requirement for many "nerdy" users of this setup.

Thanks in advance!

**Comment by agabani** [comment]
In the current architecture, the `tor` container in the `onion-balance` pod binds the control port to `127.0.0.1:6666`, All containers within the same pod can then connect to the control port (example: `onion-balance` container).

![tor-operator-baseline](https://github.com/agabani/tor-operator/assets/6744596/2607c464-3626-4067-9291-6d7639b56c85)

This pattern could be extended to allow end-users to provide their own containers (example: `sidecar-1` ... `sidecar-n`). This is similar to how extensions work in Envoy.

![tor-operator-proposal](https://github.com/agabani/tor-operator/assets/6744596/73eede07-384d-4a50-b00e-aed42e10d475)

> I would like to use the control port on an OnionService to be able to kill specific onion curcuits to prevent flooding attacks.

In your use-case, could your extension be packaged as a container to be deployed inside every pod?
